export const menu = [
  {
    id: 'id_01',
    name: '鸡翅鸡爪煲',
    type: '肉类',
    ingredients: '鸡翅、鸡爪、生姜、蒜、料酒、酱油、辣椒',
    recipe: '鸡翅和鸡爪焯水后，与姜蒜爆香，加入酱油和适量清水焖煮至入味。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_02',
    name: '西红柿鸡蛋',
    type: '蔬菜',
    ingredients: '西红柿、鸡蛋、葱、盐、糖',
    recipe: '鸡蛋炒至蓬松盛出，西红柿翻炒出汁后加入鸡蛋一起调味即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_03',
    name: '炒青菜',
    type: '蔬菜',
    ingredients: '青菜、蒜、盐、油',
    recipe: '热锅爆香蒜末，下青菜大火快速翻炒至断生即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_04',
    name: '酸笋牛肉',
    type: '肉类',
    ingredients: '牛肉、酸笋、姜、蒜、辣椒',
    recipe: '牛肉滑油备用，酸笋爆香，加入牛肉一起翻炒入味即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_05',
    name: '黑椒口蘑牛肉',
    type: '肉类',
    ingredients: '牛肉、口蘑、黑椒汁、洋葱',
    recipe: '牛肉炒至变色，加入口蘑与黑椒汁快速翻炒收汁。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_06',
    name: '辣椒小炒肉',
    type: '肉类',
    ingredients: '五花肉、青红辣椒、蒜、豆豉',
    recipe: '五花肉煸香出油，加入辣椒与豆豉爆炒均匀即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_07',
    name: '可乐鸡翅',
    type: '肉类',
    ingredients: '鸡翅、可乐、酱油、姜',
    recipe: '煎香鸡翅，倒入可乐和酱油小火炖至收汁即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_08',
    name: '土豆烧牛肉',
    type: '肉类',
    ingredients: '牛肉、土豆、姜、酱油、八角',
    recipe: '牛肉焯水后与土豆一起炖煮至软烂入味。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_09',
    name: '三汁焖锅',
    type: '其他',
    ingredients: '鸡肉、土豆、藕、胡萝卜、焖锅酱',
    recipe: '准备好三种主料，加酱料小火焖煮至熟软即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_10',
    name: '糖醋排骨',
    type: '肉类',
    ingredients: '排骨、糖、醋、酱油、姜',
    recipe: '排骨焯水后炸香，加入糖醋汁收浓即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_11',
    name: '鸡蛋火腿',
    type: '肉类',
    ingredients: '鸡蛋、火腿、盐、油',
    recipe: '火腿爆香后加入鸡蛋液炒至凝固即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_12',
    name: '腊肠鸡蛋',
    type: '肉类',
    ingredients: '腊肠、鸡蛋、葱',
    recipe: '腊肠煸香后倒入鸡蛋炒匀即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_13',
    name: '葱油炒鸡',
    type: '肉类',
    ingredients: '鸡肉、葱、姜、酱油',
    recipe: '葱姜爆香后炒鸡肉，加入葱油提香即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_14',
    name: '韭菜鸡蛋',
    type: '蔬菜',
    ingredients: '韭菜、鸡蛋、盐',
    recipe: '鸡蛋炒散后加入韭菜快速翻炒即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_15',
    name: '麻辣烫',
    type: '其他',
    ingredients: '各类蔬菜、丸子、辣汤底',
    recipe: '准备食材后放入麻辣底汤中煮熟即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_16',
    name: '葱花炒鸡蛋',
    type: '蔬菜',
    ingredients: '鸡蛋、葱花、盐',
    recipe: '热锅下蛋液，加入葱花翻炒至蓬松即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_17',
    name: '胡萝卜炒鸡蛋',
    type: '蔬菜',
    ingredients: '胡萝卜、鸡蛋、葱',
    recipe: '胡萝卜丝炒软后加入鸡蛋炒匀即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_18',
    name: '炖猪蹄',
    type: '肉类',
    ingredients: '猪蹄、姜、酱油、料酒',
    recipe: '猪蹄焯水后入锅，加调料慢炖至软糯即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_19',
    name: '烤排骨',
    type: '肉类',
    ingredients: '排骨、黑椒、盐、蜂蜜',
    recipe: '排骨腌制后放入烤箱烤至金黄即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_20',
    name: '芹菜猪肉',
    type: '肉类',
    ingredients: '猪肉、芹菜、姜、蒜',
    recipe: '先炒肉后加入芹菜大火翻炒即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_21',
    name: '胡萝卜炒猪肉',
    type: '肉类',
    ingredients: '猪肉、胡萝卜、姜',
    recipe: '猪肉滑炒后加入胡萝卜片翻炒熟透即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_22',
    name: '炒牛肉丸鱼豆腐',
    type: '肉类',
    ingredients: '牛肉丸、鱼豆腐、蒜、辣椒',
    recipe: '丸子与鱼豆腐一起炒香，加少量水焖煮入味。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_23',
    name: '肉沫豆角',
    type: '肉类',
    ingredients: '猪肉末、豆角、蒜',
    recipe: '豆角炒软后加入肉沫翻炒，加少量水焖熟即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_24',
    name: '芋头扣肉',
    type: '肉类',
    ingredients: '五花肉、芋头、酱油、姜',
    recipe: '五花肉与芋头码好蒸至软糯即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_25',
    name: '腊肠炒荷兰豆',
    type: '肉类',
    ingredients: '腊肠、荷兰豆、蒜',
    recipe: '腊肠煸香后加入荷兰豆大火翻炒即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_26',
    name: '鸡蛋肉片汤',
    type: '汤',
    ingredients: '鸡蛋、猪肉片、葱、盐',
    recipe: '肉片煮熟后倒入蛋液搅散，调味即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_27',
    name: '炒鸡蛋豆腐',
    type: '其他',
    ingredients: '鸡蛋、豆腐、葱',
    recipe: '豆腐煎香后加入鸡蛋一起翻炒即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_28',
    name: '鸡肉蘑菇',
    type: '肉类',
    ingredients: '鸡肉、蘑菇、姜蒜',
    recipe: '鸡肉翻炒变色后加入蘑菇焖煮入味即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_29',
    name: '烧鸭',
    type: '肉类',
    ingredients: '鸭肉、酱油、香料',
    recipe: '腌制鸭肉后焖煮或烧至入味。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_30',
    name: '梅花肉',
    type: '肉类',
    ingredients: '梅花肉、酱油、姜蒜',
    recipe: '梅花肉切片快炒，加入酱汁翻炒入味。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_31',
    name: '鸡蛋豆腐汤',
    type: '汤',
    ingredients: '鸡蛋、豆腐、葱',
    recipe: '豆腐煮开后淋蛋液，轻搅即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_32',
    name: '排骨汤',
    type: '汤',
    ingredients: '排骨、姜、盐',
    recipe: '排骨炖至汤白，加盐调味即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_33',
    name: '鱼豆腐',
    type: '其他',
    ingredients: '鱼豆腐、蒜、酱油',
    recipe: '煎香鱼豆腐后加少量水焖煮入味。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_34',
    name: '青笋牛肉',
    type: '肉类',
    ingredients: '牛肉、青笋、姜蒜',
    recipe: '牛肉炒至变色，加入青笋大火快炒即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_35',
    name: '青笋猪肉',
    type: '肉类',
    ingredients: '猪肉、青笋、蒜',
    recipe: '猪肉炒香后加入青笋翻炒入味。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_36',
    name: '番茄牛腩',
    type: '肉类',
    ingredients: '牛腩、西红柿、姜',
    recipe: '牛腩炖软后加入西红柿继续煮入味。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_37',
    name: '炒藕片',
    type: '蔬菜',
    ingredients: '藕片、蒜、辣椒',
    recipe: '藕片焯水后爆炒，加盐即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_38',
    name: '云吞',
    type: '主食',
    ingredients: '云吞皮、猪肉馅',
    recipe: '云吞包好后煮熟配汤即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_39',
    name: '饺子',
    type: '主食',
    ingredients: '饺子皮、肉馅或蔬菜馅',
    recipe: '饺子煮至漂浮即可食用。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_40',
    name: '米皮饺子',
    type: '主食',
    ingredients: '米皮、肉馅',
    recipe: '包好后蒸或煮熟即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_41',
    name: '八宝粥',
    type: '主食',
    ingredients: '红豆、绿豆、花生、莲子、薏米等',
    recipe: '八种杂粮浸泡后小火煮成浓稠粥。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_42',
    name: '黄豆浆',
    type: '其他',
    ingredients: '黄豆、水、糖',
    recipe: '浸泡黄豆后打成浆，过滤煮熟即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_43',
    name: '黑豆浆',
    type: '其他',
    ingredients: '黑豆、水、糖',
    recipe: '浸泡黑豆，加水打浆煮熟即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_44',
    name: '清蒸虾',
    type: '海鲜',
    ingredients: '鲜虾、姜、料酒',
    recipe: '虾加料酒和姜蒸至变红即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_45',
    name: '咖喱虾',
    type: '海鲜',
    ingredients: '虾、咖喱、椰浆',
    recipe: '虾煸香后加入咖喱煮至入味即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_46',
    name: '青椒酿虾滑',
    type: '海鲜',
    ingredients: '虾滑、青椒、葱',
    recipe: '青椒塞入虾滑煎至熟透即可。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_47',
    name: '清炒土豆丝',
    type: '蔬菜',
    ingredients: '土豆、辣椒、蒜',
    recipe: '土豆丝大火快炒，加醋提味。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_48',
    name: '干锅土豆片',
    type: '蔬菜',
    ingredients: '土豆片、干锅底料',
    recipe: '土豆片煎香后加干锅料翻炒。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_49',
    name: '青椒酿肉',
    type: '肉类',
    ingredients: '青椒、肉馅、葱',
    recipe: '青椒塞肉馅煎香后加水焖熟。',
    pictures: [],
    price: 0,
  },
  {
    id: 'id_50',
    name: '香煎豆腐',
    type: '蔬菜',
    ingredients: '豆腐、盐、葱',
    recipe: '豆腐煎至两面金黄，加盐调味即可。',
    pictures: [],
    price: 0,
  },
];
